package com.uam.springboot.manager.app.model.catalogos;

public enum TIPOAMBIENTE {

    AULA,
    AUDITORIO,
    SALA_DE_REUNION_TUTORIAS,
    AUDITORIO_CENTRAL,
    CICLOGRAMA_SET_DE_FOTOGRAFIA,
    JAGUAR_CENTER,
    CANCHA_DE_SOFTBOL,
    CANCHA_DE_FUTBOL,
    TALLER_SALA_DE_DIBUJO,

}
